"""test

Revision ID: c58816d6e760
Revises: cf119ce8179b
Create Date: 2024-06-02 22:33:23.811140

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c58816d6e760'
down_revision = 'cf119ce8179b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('title1', sa.String(), nullable=True))
    op.add_column('blog_post', sa.Column('title2', sa.String(), nullable=True))
    op.add_column('blog_post', sa.Column('paragraph1', sa.String(), nullable=True))
    op.add_column('blog_post', sa.Column('paragraph2', sa.String(), nullable=True))
    op.add_column('blog_post', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.alter_column('blog_post', 'image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('blog_post', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('blog_post', 'image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('blog_post', 'creator_id')
    op.drop_column('blog_post', 'paragraph2')
    op.drop_column('blog_post', 'paragraph1')
    op.drop_column('blog_post', 'title2')
    op.drop_column('blog_post', 'title1')
    # ### end Alembic commands ###
