"""test

Revision ID: cf119ce8179b
Revises: 6c69b13b7399
Create Date: 2024-06-02 13:03:30.722346

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'cf119ce8179b'
down_revision = '6c69b13b7399'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('title', sa.String(), nullable=False))
    op.add_column('blog_post', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('blog_post', sa.Column('synopsis', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_post', 'synopsis')
    op.drop_column('blog_post', 'created_at')
    op.drop_column('blog_post', 'title')
    # ### end Alembic commands ###
